<ModuleDefinition
	ModuleId="Core_GameObjects"
	VersionId="1"
	Description="Module that implements the core engine-level setup for the game."
	ScriptFile="Core_GameObjects.cs"
	CreateFunction="onCreate"
	DestroyFunction="onDestroy"
	Group="Core">
	<DeclaredAssets
           canSave="true"
           canSaveDynamicFields="true"
           Extension="asset.taml"
           Recurse="true" />
	<AutoloadAssets
	   canSave="true"
	   canSaveDynamicFields="true"
	   AssetType="GameObjectAsset"
	   Recurse="true" />
</ModuleDefinition>