# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = '2'

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = 'ubuntu/trusty32'

  config.vm.provider 'virtualbox' do |vb|
    vb.gui = true
    vb.memory = 1024
  end

  config.vm.synced_folder '../../', '/torque'

  config.vm.provision :shell, path: 'provision.sh'

  # config.vm.network 'forwarded_port', guest: 80, host: 8080

  # More info at http://fgrehm.viewdocs.io/vagrant-cachier/usage
  if Vagrant.has_plugin?('vagrant-cachier')
    config.cache.scope = :box
  end
end
