language: cpp

dist: xenial

matrix:
  include:
    - os: osx
      compiler: clang
      env: if CXXFLAGS="-fgnu-inline-asm -fasm-blocks"
    - os: linux
      compiler: gcc
    - os: linux
      compiler: clang

addons:
  apt:
    packages:
      - build-essential
      - nasm
      - libogg-dev
      - libxft-dev
      - libx11-dev
      - libxxf86vm-dev
      - libopenal-dev
      - libfreetype6-dev
      - libxcursor-dev
      - libxinerama-dev
      - libxi-dev
      - libxrandr-dev
      - libxss-dev
      - libglu1-mesa-dev
      - libgtk-3-dev

script:
  - mkdir -p My\ Projects/TestProject/buildFiles/travis/
  - cd My\ Projects/TestProject/buildFiles/travis/
  - cmake ../../../.. -DTORQUE_APP_NAME=TestProject -DCMAKE_BUILD_TYPE=Debug
  - make 2>/dev/null # Do the actual build, but ignore all the warnings
  - make # build again. This time all output is printed but the warnings that happened earlier do not happen again
  - make install
  - cd ../../game/
  - ls
