language: cpp
dist: xenial
compiler:
  - clang
  - gcc

install:
  - sudo apt-get install build-essential nasm xorg-dev ninja-build gcc-multilib g++-multilib cmake
  - sudo apt-get install libogg-dev libxft-dev libx11-dev libxxf86vm-dev libopenal-dev libfreetype6-dev libxcursor-dev libxinerama-dev libxi-dev libxrandr-dev libxss-dev libglu1-mesa-dev
  - sudo apt-get install build-essential libgtk-3-dev

script:
  - pwd
  - ls
  - cp -r Templates/BaseGame/ My\ Projects/
  - mkdir My\ Projects/BaseGame/buildFiles/
  - mkdir My\ Projects/BaseGame/buildFiles/travis/
  - cd My\ Projects/BaseGame/buildFiles/travis/
  - pwd
  - cmake ../../../.. -DTORQUE_APP_NAME=BaseGame -DCMAKE_BUILD_TYPE=Release -Wno-deprecated
  - ls
  - make 2>/dev/null # Do the actual build, but ignore all the warnings
  - make # build again. This time all output is printed but the warnings that happened earlier do not happen again
  - cd ../../game/
  - ls
