language: cpp
dist: xenial
compiler:
  - clang
  - gcc

install:
  - sudo apt-get install git build-essential nasm xorg-dev ninja-build gcc-multilib g++-multilib cmake cmake-qt-gui
  - sudo apt-get install libogg-dev libxft-dev libx11-dev libxxf86vm-dev libopenal-dev libfreetype6-dev libxcursor-dev libxinerama-dev libxi-dev libxrandr-dev libxss-dev libglu1-mesa-dev
  - sudo apt-get install build-essential libgtk-3-dev

script:
  - pwd
  - ls
  - cp -r Templates/BaseGame/ My\ Projects/
  - mkdir My\ Projects/BaseGame/buildFiles/
  - mkdir My\ Projects/BaseGame/buildFiles/travis/
  - cd My\ Projects/BaseGame/buildFiles/travis/
  - pwd
  - cmake ../../../.. -DTORQUE_APP_NAME=BaseGame -DCMAKE_BUILD_TYPE=Debug
  - ls
  - make
  - cd ../../game/
  - ls
