.TH JNG 5 "July 26, 2000"
.SH NAME
jng \- JPEG Network Graphics (JNG) sub-format
.SH DESCRIPTION
JNG (JPEG Network Graphics) is a sub-format of the MNG (Multiple-image
Network Graphics) format. As with MNG it extends on the features of the
popular PNG (Portable Network Graphics) image-format. 
.br

This sub-format was designed to support a lossy compression-method.
It is based completely on the JPEG specification. It adds the high-compression
ratios of JPEG for photographic images.

As a member of the Network Graphics family, JNG was deemed adequate as a
stand-alone format as it extends the JPEG format with color-correction and
transparency features.

.SH "SEE ALSO"
.IR png(5) ", " mng(5) ", " libmng(3)
.LP
MNG 1.00, February 9, 2001:
.IP
http://www.libpng.org/pub/mng

.SH AUTHORS
This man page: Gerard Juyn
.LP
Multiple-image Network Graphics (MNG) Specification Version 1.00 (Februari 9, 2001):
Glenn Randers-Pehrson and others (png-list@ccrc.wustl.edu).
.LP

.SH COPYRIGHT NOTICE
The MNG-1.00 specification is copyright (c) 1998-2001 Glenn Randers-Pehrson.
See the specification for conditions of use and distribution.
.LP
.\" end of man page

