<ModuleDefinition
	ModuleId="CoreComponentsModule"
	VersionId="1"
	Description="Module that implements the core engine-level components for the game."
	ScriptFile="CoreComponents.cs"
	CreateFunction="onCreate"
	DestroyFunction="onDestroy"
	Group="Game">
	<DeclaredAssets
           canSave="true"
           canSaveDynamicFields="true"
           Extension="asset.taml"
           Recurse="true" />
	<AutoloadAssets
	   canSave="true"
	   canSaveDynamicFields="true"
	   AssetType="ComponentAsset"
	   Recurse="true" />
</ModuleDefinition>